"""1Password SDK integration for PSK storage."""

import asyncio
import logging
import os

logger = logging.getLogger(__name__)

OP_SERVICE_ACCOUNT_TOKEN = os.environ.get("OP_SERVICE_ACCOUNT_TOKEN", "")
OP_VAULT_UUID = os.environ.get("OP_VAULT_UUID", "")

# When OP_DEV_BYPASS=true the PSK is written to a local temp file instead of
# 1Password.  The Nautobot Secret is created with the built-in "text-file"
# provider so the job can retrieve the PSK without any external credentials.
# Never enable this in production.
_DEV_PSK_DIR = "/tmp/nautobot-dev-psk"  # noqa: S108


def _dev_bypass_enabled():
    return os.environ.get("OP_DEV_BYPASS", "").lower() in ("true", "1", "yes")


def store_psk_in_1password(psk, member_name, location_slug, sequence):
    """Create a 1Password item containing the PSK for a member tunnel.

    Args:
        psk: The pre-shared key value.
        member_name: Member slug (e.g., "acme-corp").
        location_slug: Location slug (e.g., "jackson-ms").
        sequence: Crypto map sequence number.

    Returns:
        The created 1Password item ID (str).

    Raises:
        RuntimeError: If 1Password credentials are not configured and dev bypass is off.
        Exception: If the 1Password SDK call fails.
    """
    if _dev_bypass_enabled():
        return _store_psk_dev_bypass(psk, member_name, location_slug, sequence)

    if not OP_SERVICE_ACCOUNT_TOKEN or not OP_VAULT_UUID:
        raise RuntimeError(
            "1Password credentials not configured. "
            "Set OP_SERVICE_ACCOUNT_TOKEN and OP_VAULT_UUID environment variables."
        )

    return asyncio.run(_create_op_item(psk, member_name, location_slug, sequence))


def get_secret_provider_params(op_item_id):
    """Return (provider, parameters) for the Nautobot Secret for this item.

    In dev bypass mode this points to the local temp file instead of 1Password.
    """
    if _dev_bypass_enabled():
        return "text-file", {"path": f"{_DEV_PSK_DIR}/{op_item_id}"}
    return "one-password", {"item_id": op_item_id, "field": "password"}


def _store_psk_dev_bypass(psk, member_name, location_slug, sequence):
    """Dev bypass: write PSK to a temp file, return a stable item ID."""
    os.makedirs(_DEV_PSK_DIR, exist_ok=True)
    item_id = f"dev-{member_name}-{location_slug}-{sequence}"
    path = os.path.join(_DEV_PSK_DIR, item_id)
    with open(path, "w") as f:  # noqa: PTH123
        f.write(psk)
    logger.warning("DEV BYPASS: PSK written to %s — not stored in 1Password", path)
    return item_id


async def _create_op_item(psk, member_name, location_slug, sequence):
    """Async helper to create the 1Password item via the SDK."""
    from onepassword import (  # pylint: disable=import-outside-toplevel,import-error
        Client,
        ItemCategory,
        ItemCreateParams,
        ItemField,
        ItemFieldType,
    )

    from . import __version__  # pylint: disable=import-outside-toplevel

    op_client = await Client.authenticate(
        auth=OP_SERVICE_ACCOUNT_TOKEN,
        integration_name="nautobot-custom-tunnel-builder",
        integration_version=__version__,
    )

    title = f"vpn-psk-nrtc-ms-{member_name}-{location_slug}-{sequence}"

    item_payload = ItemCreateParams(
        vault_id=OP_VAULT_UUID,
        category=ItemCategory.LOGIN,
        title=title,
        fields=[
            ItemField(
                id="password",
                title="Pre-Shared Key",
                value=psk,
                fieldType=ItemFieldType.CONCEALED,
            ),
        ],
        notes=f"Auto-generated by Custom Tunnel Builder for {member_name} at {location_slug}.",
    )

    logger.info("Creating 1Password item '%s' in vault '%s'.", title, OP_VAULT_UUID)
    created_item = await op_client.items.create(item_payload)
    logger.info("Created 1Password item '%s' (ID: %s).", created_item.title, created_item.id)

    return created_item.id
