"""1Password SDK integration for PSK storage."""

import asyncio
import logging
import os

from django.conf import settings

logger = logging.getLogger(__name__)

OP_SERVICE_ACCOUNT_TOKEN = os.environ.get("OP_SERVICE_ACCOUNT_TOKEN", "")
OP_VAULT_UUID = os.environ.get("OP_VAULT_UUID", "")

# When OP_DEV_BYPASS=true the PSK is written to a local temp file instead of
# 1Password.  The Nautobot Secret is created with the built-in "text-file"
# provider so the job can retrieve the PSK without any external credentials.
# Never enable this in production.
_DEV_PSK_DIR = "/tmp/nautobot-dev-psk"  # noqa: S108


def _dev_bypass_enabled():
    """Dev bypass requires BOTH the OP_DEV_BYPASS env var and settings.DEBUG."""
    if os.environ.get("OP_DEV_BYPASS", "").lower() not in ("true", "1", "yes"):
        return False
    if not settings.DEBUG:
        logger.warning(
            "OP_DEV_BYPASS is set but settings.DEBUG is False — bypass DISABLED; " "PSKs will be stored in 1Password."
        )
        return False
    logger.warning(
        "OP_DEV_BYPASS ACTIVE: PSKs are written to %s instead of 1Password. " "Never enable this in production.",
        _DEV_PSK_DIR,
    )
    return True


def _psk_item_note(**fields):
    """Build the 1Password item note: operator context so an engineer finding
    the PSK can identify its tunnel without opening Nautobot. Blank/None fields
    are omitted rather than rendered as empty lines."""
    header = [
        "Pre-shared key for an NRTC site-to-site IPsec VPN tunnel.",
        "Auto-generated by Nautobot Custom Tunnel Builder — managed automatically; do not edit.",
    ]
    labels = [
        ("member", "Member"),
        ("location", "Location"),
        ("remote_peer_ip", "Member peer IP"),
        ("hub_device", "NRTC hub device"),
        ("sequence", "Crypto map sequence"),
        ("request_id", "Member Connect request"),
    ]
    body = [f"{label}: {fields[key]}" for key, label in labels if fields.get(key) not in (None, "")]
    return "\n".join(header + body)


def store_psk_in_1password(psk, member_name, location_slug, sequence, note_context=None):
    """Create a 1Password item containing the PSK for a member tunnel.

    Args:
        psk: The pre-shared key value.
        member_name: Member slug (e.g., "acme-corp").
        location_slug: Location slug (e.g., "jackson-ms").
        sequence: Crypto map sequence number.

    Returns:
        The created 1Password item ID (str).

    Raises:
        RuntimeError: If 1Password credentials are not configured and dev bypass is off.
        Exception: If the 1Password SDK call fails.
    """
    if _dev_bypass_enabled():
        return _store_psk_dev_bypass(psk, member_name, location_slug, sequence)

    if not OP_SERVICE_ACCOUNT_TOKEN or not OP_VAULT_UUID:
        raise RuntimeError(
            "1Password credentials not configured. "
            "Set OP_SERVICE_ACCOUNT_TOKEN and OP_VAULT_UUID environment variables."
        )

    return asyncio.run(_create_op_item(psk, member_name, location_slug, sequence, note_context=note_context))


def get_secret_provider_params(op_item_id):
    """Return (provider, parameters) for the Nautobot Secret for this item.

    In dev bypass mode this points to the local temp file instead of 1Password.
    """
    if _dev_bypass_enabled():
        return "text-file", {"path": f"{_DEV_PSK_DIR}/{op_item_id}"}
    # Shape must match what NTC nautobot-secrets-providers' one-password
    # provider reads (vault/item/field → op://vault/item/field). vault is the
    # SDK write target (OP_VAULT_UUID); item is the created item id.
    return "one-password", {"vault": os.environ.get("OP_VAULT_UUID", ""), "item": op_item_id, "field": "password"}


def delete_psk_from_1password(op_item_id):
    """Delete the 1Password item holding a tunnel's PSK (used on teardown).

    Best-effort: callers treat failure as non-fatal and log it, since an
    orphaned secret is preferable to a failed teardown. In dev bypass mode the
    backing temp file is removed instead.
    """
    if not op_item_id:
        return
    if _dev_bypass_enabled():
        path = os.path.join(_DEV_PSK_DIR, op_item_id)
        if os.path.exists(path):  # noqa: PTH110
            os.remove(path)  # noqa: PTH107
            logger.warning("DEV BYPASS: removed PSK temp file %s", path)
        return
    asyncio.run(_delete_op_item(op_item_id))


async def _delete_op_item(op_item_id):
    """Async helper to delete a 1Password item via the SDK."""
    from onepassword import Client  # pylint: disable=import-outside-toplevel,import-error

    from . import __version__  # pylint: disable=import-outside-toplevel

    op_client = await Client.authenticate(
        auth=OP_SERVICE_ACCOUNT_TOKEN,
        integration_name="nautobot-custom-tunnel-builder",
        integration_version=__version__,
    )
    logger.info("Deleting 1Password item '%s' from vault '%s'.", op_item_id, OP_VAULT_UUID)
    await op_client.items.delete(OP_VAULT_UUID, op_item_id)


def _store_psk_dev_bypass(psk, member_name, location_slug, sequence):
    """Dev bypass: write PSK to a temp file, return a stable item ID."""
    os.makedirs(_DEV_PSK_DIR, exist_ok=True)
    item_id = f"dev-{member_name}-{location_slug}-{sequence}"
    path = os.path.join(_DEV_PSK_DIR, item_id)
    with open(path, "w") as f:  # noqa: PTH123
        f.write(psk)
    logger.warning("DEV BYPASS: PSK written to %s — not stored in 1Password", path)
    return item_id


async def _create_op_item(psk, member_name, location_slug, sequence, note_context=None):
    """Async helper to create the 1Password item via the SDK."""
    from onepassword import (  # pylint: disable=import-outside-toplevel,import-error
        Client,
        ItemCategory,
        ItemCreateParams,
        ItemField,
        ItemFieldType,
    )

    from . import __version__  # pylint: disable=import-outside-toplevel

    op_client = await Client.authenticate(
        auth=OP_SERVICE_ACCOUNT_TOKEN,
        integration_name="nautobot-custom-tunnel-builder",
        integration_version=__version__,
    )

    title = f"vpn-psk-nrtc-ms-{member_name}-{location_slug}-{sequence}"

    item_payload = ItemCreateParams(
        vault_id=OP_VAULT_UUID,
        category=ItemCategory.LOGIN,
        title=title,
        fields=[
            ItemField(
                id="password",
                title="Pre-Shared Key",
                value=psk,
                fieldType=ItemFieldType.CONCEALED,
            ),
        ],
        notes=_psk_item_note(**(note_context or {"member": member_name, "location": location_slug, "sequence": sequence})),
    )

    logger.info("Creating 1Password item '%s' in vault '%s'.", title, OP_VAULT_UUID)
    created_item = await op_client.items.create(item_payload)
    logger.info("Created 1Password item '%s' (ID: %s).", created_item.title, created_item.id)

    return created_item.id
